### ISSUE TITLE
Writing replaces text instead of moving it to the right

### ISSUE THREAD

**Issue by imiMike** [webextensions/live-css-editor#1]
[Recording #4.zip](https://github.com/webextensions/live-css-editor/files/954842/Recording.4.zip)

**Comment by webextensions** [comment]
It seems to be just a case of reaching the "Insert" mode by pressing the "Insert" key.

Of course, from the UI, it was not clear that editing is happening in "Insert' mode.

In https://github.com/webextensions/live-css-editor/commit/85cd1ea7cbb4a7fbcf57295d52addea923d25b2d I have added styling so that the cursor would start looking like a block when the eitor is in "Insert" mode.

**Such an edit mode change would be easily noticeable after the above mentioned commit. I'll include this update in the Chrome extension within a few days (along with some other improvements).**

@imiMike 
Kindly reopen if there was anything more to this issue.
