### ISSUE TITLE
Sass?  Scss?

### ISSUE THREAD

**Issue by spinweb1** [webextensions/live-css-editor#118]
Hi there!  I love this extension and was excited to try it with SASS, but when I put in my .scss
code nothing seems to happen.  Only Less is mentioned in the popup.  I only see SASS on the
extension page, but not on the tool itself.

Am I missing something?

Thanks!  Eric

**Comment by webextensions** [comment]
@spinweb1 
Can you check if the information provided in the following issues/discussions resolves the issue for you?

* https://github.com/webextensions/live-css-editor/issues/68
* https://github.com/webextensions/live-css-editor/issues/92 / https://github.com/webextensions/live-css-editor/discussions/91

If your concern is not covered in these, can you please add more details?

Otherwise, if your concern is covered, do you have any suggestions what UI / UX update might serve the concern in clear manner for other new users?

**Comment by webextensions** [comment]
Assuming that the linked issues provide a decent explanation / workaround. Marking resolved.

**Comment by spinweb1** [comment]
Hi there,
Sorry for delay. Many distractions around holidays.  

I see the "sass" link in the popup on Chrome, but not on Firefox.  It seems to work in Chrome.Is it supposed to be present in Firefox?

Thanks, Eric


    On Thursday, January 12, 2023 at 03:15:23 PM EST, webextensions ***@***.***> wrote:  
 
 


Assuming that the linked issues provide a decent explanation / workaround. Marking resolved.

**Comment by webextensions** [comment]
Thank you for confirming that it is working fine in Chrome.

In Firefox, "Sass" mode is disabled in the current version due to their hectic (and potentially more secure) review process. Some more details regarding that are available at https://github.com/webextensions/live-css-editor/issues/49#issuecomment-779580848

A "TODO" note has been added to publish the latest version on different browsers (https://github.com/webextensions/live-css-editor/commit/aad29992bfe739eb72ee6b856019babf4b07df8c).

**Comment by webextensions** [comment]
PS: Some more information about when to expect local SASS parser is available at https://github.com/webextensions/live-css-editor/issues/86#issuecomment-1189520438
