### ISSUE TITLE
Feature request: ability to disable class finder temporarily + a bit brighter comments color

### ISSUE THREAD

**Issue by Nikodemsky** [webextensions/live-css-editor#139]
Hi,

using addon for years now and loving it, but there's two things that still kinda could be... "fixed",

1. first thing would be class finder, i'm mostly using small window to enter code and often class finder overlaps my code, it's kinda annoying :\ It looks like this:
![classf2](https://github.com/webextensions/live-css-editor/assets/14090596/82270d54-3621-4fd0-a2b4-db12317a10f5)
- as you can see last two lines are practically hidden under class finder and i need to wait for it to dissapear. I would love possibility to have it hidden - temporarily with button alongside other quickbuttons at top would be perfect.

2. Comments are kinda hard to read while coding at day, can you make it just a little bit brighter?

**Comment by webextensions** [comment]
@Nikodemsky

Thank you for the report. The mentioned issues have been fixed now :smile:

1. Now using unobtrusive notifications when finding matches for the CSS selector (when the editor is opened in external window). The notifications would go away if mouse hovers on them (https://github.com/webextensions/live-css-editor/commit/4ff062d7100e1589a63887b7809798743d5336c7). This was the quickest solution while ensuring minimal UI interaction. Hope that it covers a good chunk of such problematic cases. In future, we may also add the "scrolling past bottom" which would also cover more instances of this problem and other use cases (Ref: https://github.com/webextensions/live-css-editor/issues/109).
2. Made the color for code comments a little brighter in the dark theme. Changed it from `rgb(85, 85, 85)` (`#555`) to `rgb(125, 125, 125)` (https://github.com/webextensions/live-css-editor/commit/89b0f4f633a3e994c0e1b00ae6f229920e813013)

The fix would be available with `v8.22.3` of the extension. Please note that it might take a little time to update the extension since the update for `v8.22.2` is already pending at the Chrome Web Store for the fix of https://github.com/webextensions/live-css-editor/issues/138
