### ISSUE TITLE
Suggestion: Space to enter predetermined variables?

### ISSUE THREAD

**Issue by mwilday** [webextensions/live-css-editor#15]
It would be fantastic to allow a settings location for pre-determining variables for SASS. I do theming for several websites where i use the same variables, to be able to have those readily available before I start tweaking code would be a HUGE timesaver. Just a thought. Thanks for a great product!

**Comment by webextensions** [comment]
@mwilday 
I believe your issue is that the variables are defined in one sass file and you wish to use them in another sass file and the code you write in Magic CSS editor doesn't understand those variables due to which your changes are not getting applied.

I believe that problem would get indirectly solved when live editing real css/less/sass files gets implemented. Reference: "Add support for editing and saving the CSS/Less/Sass files" (https://github.com/webextensions/live-css-editor/blob/master/TODO.md#new-features)

**Comment by mwilday** [comment]
Possibly, but I am editing SASS on a Moodle LMS theme and I don't have direct or editable access to the sheet itself. I am having to use a code editor window which compiles my code into the system. I'd like to be able to set up a set of variables that I can expect to use anytime i use the magic CSS editor and then just enter my variables without having to add them to the top of my edits. Does that make sense? I'd like them hard-coded in (so to speak) based on an option window or something so anytime I edit code on a page the editor will reference my variables.

**Comment by webextensions** [comment]
@mwilday 
Your suggested solution would probably work well for your use case, by having some sort of global setting which contains the value to prepend.

Can you provide a little more detailed step-by-step workflow you follow? I wish to understand your use case a little more to identify the pain points, abilities and limitations of your workflow.

Not promising a quick final solution :-)
**But, I might be able to provide a workaround bookmarklet code for your scenario while an acceptable solution is not integrated to Magic CSS.** (Please mention your browser as well)

**Comment by mwilday** [comment]
Sure... One of the sites I am responsible for is course.uc.apu.edu, soon to be course.lapu.edu. When i am troubleshooting CSS or display issues or working on themes in a course I will: 

1. load up a course page
2. open the css editor
3. begin troubleshooting CSS
4. If my code is successful I then have to go to an admin settings page which contains a field for my SASS code and i have to add the css there. 
5. After pasting my code I would then apply the color variables. 

Having prepended values would allow me to use variables for more  than just colors. I have variables for borders for our themes, and such. When I troubleshoot with a live editor I always have to type in the variables first, or type in the full code. My end result would be much cleaner if I could just troubleshoot using the variables I use already!  This would be a splendid option. Let me know if you have any other questions.

**Comment by webextensions** [comment]
@mwilday 
I am assuming you would be having a single block of code which would be declaring Sass variables in your code.

Magic CSS remembers the code you type there for the next reload and it is applicable for all webpages for a given domain name. **So, what is/are the reasons due to which you don't want to copy-paste that Sass variables code into Magic CSS editor and make your fixes at the bottom of the editor?**
- You wish to avoid that clutter in the editor?
- Those Sass variables change often?
- It is not just Sass variables but some more stuff that you need to reuse?
- You work on various sites and you wish to avoid copy-pasting?
- You work on various sites and often switch browsers/computers?
- You often use private browsing mode due to which Magic CSS editor doesn't remember code?

**Comment by webextensions** [comment]
@mwilday 
I gave it some thought, but couldn't come up with any solution which would be simple enough to implement and/or would be simple enough for the users to understand (and not get confused with the additional UI).

I believe that for users editing the real files, a major part of this issue would get solved with the live editing and saving task mentioned in https://github.com/webextensions/live-css-editor/blob/master/TODO.md#new-features

Unfortunately, your use case (where you don't work with files directly) is rare which may not fit well with the limited scope of this extension.

I would prefer to mark it closed as a Won't Do.
