### ISSUE TITLE
Not working on Edge

### ISSUE THREAD

**Issue by goranalkovic** [webextensions/live-css-editor#17]
After downloading the Edge version (not available in Store btw) as a zip and loading it, when I click on the editor button it does nothing.

**Comment by webextensions** [comment]
@goranalkovic 
Yes, it got unpublished from store due to missing "Privacy Policy".

I'll check the issue you mentioned and update the newer version in all remaining browsers (Chrome has the latest version).

Note: "Reapply CSS changes" feature works well in Chrome. On Firefox, it wouldn't be available due to the issue mentioned at https://github.com/webextensions/live-css-editor/blob/master/TODO.md#improvements. On Edge, I'll need to check.

**Comment by webextensions** [comment]
@goranalkovic 
I have now fixed the issues with Microsoft Edge extension.
I'll try to publish it on the store now.

In the meantime, if you wish to use it, you may follow the steps mentioned at:
https://github.com/webextensions/live-css-editor/blob/master/notes-for-developers.md#for-edge--firefox

I'll resolve this issue once the extension is published to the store.

**Comment by webextensions** [comment]
The older version of the extension is now available for Microsoft Edge.
The newer version should also become available within a few days.
