### ISSUE TITLE
Changes aren't applied after reload until extension is opened

### ISSUE THREAD

**Issue by EmmanuelMess** [webextensions/live-css-editor#2]
Chrome 58.0.3029.110 (64-bit), Windows 10
If I change the css of a page and reload, changes aren't applied until I open the extension again. There should at least be a configuration that allows that.

**Comment by webextensions** [comment]
@EmmanuelMess 

The main reason behind not doing that is security concerns a user might have.

**Let me explain:**
As you might have noticed, many of the browser extensions request permissions to access all your data across all the sites at the time you are installing them. As a user, I would not want to give an extension such rights. What if such an extension steals data/password from my email or bank site.

But, in case of Magic CSS extension, it doesn't ask you any permissions at all because it doesn't run in background for every page. It only runs when the user clicks on the icon. It uses something called "activeTab" permission from the browser, which only has access to the currently active tab and hence Chrome doesn't show any warnings which might scare the user.

I remember that once I tried to make it auto-run, while avoiding need of full data access, but it didn't seem to be possible due to Chrome's architecture for extensions.

**Solution:**
You might try out Stylish/Stylebot or other such extensions. I believe they would cover this requirement (while asking you full access permissions).

Later on, if Chrome makes it possible while keeping security concerns to minimal, I may try it. Till then, marking this issue as Closed.

**Comment by EmmanuelMess** [comment]
I understand

**Comment by webextensions** [comment]
@EmmanuelMess 

I have added a TODO task for this at https://github.com/webextensions/live-css-editor/blob/master/TODO.md under "Improvements".

Though it might take some time before I look into it.

**Comment by paras20xx** [comment]
Implementing this would be possible with dynamic permissions (would work at least on Chrome).

Reopening this.

**Comment by webextensions** [comment]
Fixed in https://github.com/webextensions/live-css-editor/commit/a1a7275ec79ec17d8b50a99eae1982b7c67b36ac

The latest version would become available on Chrome in a few minutes.

For Firefox/Edge/Opera, I'll verify that it works well and upload there too.
Added a TODO task for that at: https://github.com/webextensions/live-css-editor/blob/master/TODO.md#improvements

**Comment by webextensions** [comment]
This doesn't yet work in Firefox due to the following bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1392624
(Also see: https://bugzilla.mozilla.org/show_bug.cgi?id=1397658)

I'll update the TODO list and keep this issue in closed state.
