### ISSUE TITLE
We need a STOP button to freeze the page for when we need to edit the CSS of a popup that only shows up when hovered.

### ISSUE THREAD

**Issue by CheatTriggers** [webextensions/live-css-editor#22]
title ^

**Comment by webextensions** [comment]
@CheatTriggers 

From what I know, it is not possible to freeze a page (apart from using browser debugger).

**Depending on whether your popup gets triggered by CSS or JavaScript**, you may try the following workarounds:

**Focus CSS editor first**
- Click on the editor to focus on CSS code editing
- Move your mouse over the other element you mentioned
- Continue typing, since the focus is on CSS code editor, it would type there and the styles would get applied

**Use browser DevTools :hov feature**
- In Chrome/Chromium based browser, open browser "DevTools" > "Elements" panel
- Select the element on whose hover you would see the popup
- Now, go to "Styles" panel (should be visible within the "Elements" panel), near the top-right, you would see ":hov", click on that
- A panel would expand, check the ":hover" option there
- Your pop-up would show and it would not go away
- Now use the CSS code editor to make the changes

**Use browser DevTools debugger**
- In browser DevTools console, run code like: `setTimeout(function () { debugger; }, 5000);`
- Now within 5 seconds, move your mouse over the area where the popup is showing
- Once the 5 seconds complete, the browser debugger would pause the execution
- Now you can make the changes via browser DevTools

I'm assuming that one of these workarounds would help you develop the CSS for the hover popup.

Closing this issue.
