### ISSUE TITLE
Feature request: Option to stay active

### ISSUE THREAD

**Issue by LeeteqXV** [webextensions/live-css-editor#27]
There is one huge inconvenience with the "workflow" of using this extension:

1. Visit a new domain, then click on the Live CSS button, add/paste some default/favourite code into the window and then close the window.
2. On every reload of that page, and also on any new page opened on the same domain, I have to click again to activate my desired custom CSS code, and then:
3. I have to close the window that pops up, because these sub-sequent times I just click on the button to activate the code, not to change it.

So on every page reload or new page, there are two unnecessary clicks involved.
When trying to work fast, with lots of new page openings, this drives me nuts.

**It would be great with an option to have the custom CSS stay active on all subsequent pages/reloads on each activated domain throughout the same browser session,**

**Desired behaviour:**

1. Visit a new domain, then click on the Live CSS button, add/paste some default/favourite code into the window and then close the window.
2. (not needed...) (The CSS code should stay active for each subsequent page reload for that same domain, and any new page loaded on that same domain, throughout the browser session.)

**Comment by webextensions** [comment]
@LeeteqXV 
Are you using this extension on Firefox?

The described feature is available for this extension on Chrome.

For Firefox, technically it is possible to achieve the same functionality, but then the extension would need to have full access to all the websites/webpages (which I wish to avoid the security concerns of the users). In Chrome, this is not an issue because it is easier to get dynamic permissions there.

Some more details can be found at:
https://github.com/webextensions/live-css-editor/blob/master/TODO.md#improvements and https://github.com/webextensions/live-css-editor/issues/2

I have thought of some workaround solution, to let Firefox users (who trust this extension and would not mind giving access to all webpages) achieve the same functionality.

@LeeteqXV 
Can you check once if the behavior in Chrome version of this extension matches your requirements?

I'll keep this task open and look for implementing that workaround for Firefox. But, I'm not sure how soon I'll be able to pick it up.

**Comment by LeeteqXV** [comment]
Hmm, I am using it on both firefox, chromium, vivaldi and google chrome, cannot see this option on any of them... (just re-checked again now).

For example, I use LiveCSS on this page now, can see my CSS customization effects, and when I choose to right-click on the tab here in Chromium and choose "duplicate". The page opens in a new/extra tab, but without the LiveCSS activated. I have to click on the button and then click to close the pop-up window each time.

**Comment by LeeteqXV** [comment]
Here are two screenshots of the settings/options and LiveCSS main window that I ahve here in Chromium right now.

In the main window, there is a "Reload all CSS resources" menu option, which I am unsure how works, I just tried it, just in case it is relevant here, but it only gives the following message:
"There are no active CSS <link> tags that need to be reloaded."

I do not think that is the relevant option here.
So where is the setting that you are referring to?
Should it not be visible inside the options window?
My LiveCSS editor version is 7.0.7 both in Chromium, Vivaldi and Google Chrome.

![browser_addons_chromium_livecss_settings_screenshot2sc02](https://user-images.githubusercontent.com/19711572/53684033-962bdb00-3d08-11e9-890f-888a9cd8d317.jpg)
![browser_addons_chromium_livecss_settings_screenshot2sc02b](https://user-images.githubusercontent.com/19711572/53684035-9b892580-3d08-11e9-835d-a6bfcf2a84ad.jpg)

**Comment by LeeteqXV** [comment]
(and all these browsers are at their latest stable versions)

**Comment by LeeteqXV** [comment]
(Btw: JUST IN CASE the implemented fix mentioned in the issue of your link #2 above here is NOT meant to be visible in the settings at all, but "just work", then IMO this should be a visible, optional setting, perhaps the default behaviour. but definetely with a way to manually decide whether it should be on or off.)

**Comment by enteryournamehere** [comment]
@LeeteqXV I think you're looking for the "pin" button (only available for Chrome):
![image](https://user-images.githubusercontent.com/11255568/53697762-06a02e00-3dd5-11e9-8bd2-86a585156261.png)

I'd love to see this feature for Firefox as well.

**Comment by LeeteqXV** [comment]
aaahhh, my goodness.
Heh, I did actually never read the tooltip text on that Pin button, as I assumed it was related to automatically open the LiveCSS editor window on the next page load for the actual domain...

Well, there it is :-)

I still think this should be visible as a tick box in the option window (as well), so that when entering new domains, the permissions popup appear automatically asking about that particular domain. Still want it to be possible to set it as a default "on", optionally.

**Comment by LeeteqXV** [comment]
A tip to avoid letting various extensions actually get to read the History:

- I use 2 extra extensions; one to automatically continuousely delete the history so that it is always blank/erased ("No History" extension by "Prettygraphics", and another called "Tabs Outliner", that lets me keep a hybrid between automatic bookmarks and sessions history out of reach by other extensions.

Both of them needs permission to access to the browsing history, the latter also a permission to show notifications. Subsequently no other extensions get any information out of the history function, even if they can access it.

#ITsecurity #MOMOCtips :-)

**Comment by webextensions** [comment]
In the current state, I consider the following constraints:

* Dynamic permissions don't work in Firefox in the same way as implemented in Chrome (the main difference is in triggering it). Due to that, reapply styles automatically won't work for Firefox.
* Use minimum permissions to do what is required.

I may consider implementing ask-for-permissions-for-all-sites-access via some appropriate UI along with the apply-styles-automatically-for-firefox TODO task.

Marking this issue as closed.
