### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by SimpleUs** [webextensions/live-css-editor#28]
Can this extension convert regular CSS to unique CSS?
For example, as the extension "CSS Path". I would like this functionality.

**Comment by webextensions** [comment]
@SimpleUs 
Can you provide a link to the extension "CSS Path" ? Assuming it is some browser extension, I did a quick search but could not find any popular extension with that name.

**Comment by SimpleUs** [comment]
Sorry. https://chrome.google.com/webstore/detail/copy-css-selector/kemkenbgbgodoglfkkejbdcpojnodnkg

**Comment by SimpleUs** [comment]
> Can you provide a link to the extension "CSS Path" ? Assuming it is some browser extension, I did a quick search but could not find any popular extension with that 

Sorry, [Copy-Css-Selector](https://chrome.google.com/webstore/detail/copy-css-selector/kemkenbgbgodoglfkkejbdcpojnodnkg).

**Comment by webextensions** [comment]
@simpleus

Can you describe your use case a little more?

Do you need that for some development purposes (probably to write CSS faster), or for some testing purposes (to identify unique elements and run some tests based on that) or for some performance reasons (to reduce the CSS size)?

Since the CSS writing style is very subjective from project to project, the current selector-suggestions in the extension are kept open ended and let the user choose the best selector.

So, I would like to understand your use case even more to decide appropriate course of action

**Comment by pnutster** [comment]
Is there a way that would allow the editing window to "float" above / on top of the page. When for example you would want to work on CSS in a mobile view, it becomes hard as the edting window is mostly 1. in the way of the page... or 2. cut off.

Hopefully there is a solution for this?

Thanks!
![Image 2019-09-16 at 10 19 56 AM](https://user-images.githubusercontent.com/4218393/64961469-f7159d80-d86b-11e9-8344-6c9d53c9db5d.png)
![Image 2019-09-16 at 10 23 12 AM](https://user-images.githubusercontent.com/4218393/64961497-04328c80-d86c-11e9-8d63-a4521751119d.png)

**Comment by webextensions** [comment]
@pnutster 
Kindly go through https://github.com/webextensions/live-css-editor/issues/36 and try to use the feature called "Watch CSS files to apply changes automatically". That may serve as a workaround for your needs.

**Comment by webextensions** [comment]
Marking this original issue closed for lack of activity.
