### ISSUE TITLE
CSS rule for background-image also affects the extension

### ISSUE THREAD

**Issue by rillig** [webextensions/live-css-editor#31]
I have defined the following CSS for the current web page:

```css
* {
    background-image: none !important;
}
```

This also affects the icons of the live-css-editor window:

![image](https://user-images.githubusercontent.com/3233724/57548745-0f2b5c80-7362-11e9-8996-01cc9d06e0ef.png)

The icons in the top right corner are not visible anymore. They can still be clicked though.
It took me a while to figure out where I could make the CSS permanent, as I could not see any icons. :)

**Comment by webextensions** [comment]
If the extension itself is implemented as a Web Component, then that would fix the issue. But, that change cannot be planned for now due to this feature being missing in Chrome / Chromium extensions (See: https://bugs.chromium.org/p/chromium/issues/detail?id=390807).

Considering this requirement as a generic use-case to hide all images, I have gone ahead to fix it via adding !important to all the background-image styles.

The fix would be available with the upcoming release.

**Comment by webextensions** [comment]
@rillig 
The feature of editor in external window is now implemented (which is not affected by the above mentioned bug) and the publish has been initiated on Chrome Web Store for the latest version (v8.9.0). It should become available within next few hours/days.
