### ISSUE TITLE
Can't apply styles to other extension in overlay

### ISSUE THREAD

**Issue by Scordavis** [webextensions/live-css-editor#34]
Can't apply styles to other extension in overlay, which appear on all sites. I mean styles appear to some other extension (etc online translate) only at one webpage, where that styles was redefined. At ohter page redefined styles is not connect.

**Comment by webextensions** [comment]
@Scordavis 
Can you provide specific details about how to reproduce this issue? That would help in identifying/fixing it.

**Comment by Scordavis** [comment]
@webextensions 
Sure. You must instal a Google Chrome extension  ["Mate translate"](https://chrome.google.com/webstore/detail/mate-translate-%E2%80%93-translat/ihmgiclibbndffejedjimfjmfoabpcke). When i change styles for their modal window, css saved only for exactly THIS modal window. In other tabs of browser styles not changes. Thanks.

**Comment by webextensions** [comment]
@Scordavis 
Is my following assumption correct?

I believe what you are expecting is that you go to http://example-one.com and run the "Mate translate" extension and add some styles for it via this extension.

After that, you go to http://example-two.com and run the "Mate translate" extension there as well. Now, you are expecting those styles to be applicable on this site as well.

But, since your styles are currently saved per origin (via localStorage), and these two sites belong to different origins, so the styles typed in the extension are not shared.

If the above mentioned assumption is correct, then that scenario is not covered by this extension.

**Comment by Scordavis** [comment]
Yes, you right. I expect exactly that result. I really dont know that new styles stored each for unique webpage. 
Is it possible to "hack" this issue?

**Comment by webextensions** [comment]
@Scordavis 
In the current architecture, it is not possible to do that. I'm preparing a change for https://github.com/webextensions/live-css-editor/issues/29 (add an option to use chrome storage, while currently only localStorage is being used to save those CSS code) which opens up the pathway to implement such a feature.

But, considering the fact that, such a feature would add more complexity (even for the user), I'll mark this issue resolved as Won't Do.

Apart from that, the expected scenario is already available via another extension called Stylish (https://chrome.google.com/webstore/detail/stylish-custom-themes-for/fjnbnpbmkenffdnngjfgmeleoegfcffe), so I recommend using that.

**Comment by Scordavis** [comment]
Great! Thanks for this ;)
