### ISSUE TITLE
Drag editor outside of the main browser window

### ISSUE THREAD

**Issue by im-mike** [webextensions/live-css-editor#36]
It would be great if you could use the editor outside of the internet browser - like the google DevTools - is that possible?

Thank you

**Comment by webextensions** [comment]
@im-mike

Would some of your requirements get resolved with the "Watch CSS files to apply changes automatically" feature of this extension available from the icons shown at the top-right (while using an external code editor).

Also, kindly have a look at the comments in https://github.com/webextensions/live-css-editor/issues/11 and https://github.com/webextensions/live-css-editor/issues/21

I'm assuming that some of your requirements may get solved to an acceptable level.

Closing this issue. If there are still some cases where you find the requested feature to be useful feel free to reopen it while describing your use case further.

**Comment by webextensions** [comment]
Please note that technically such a feature would be possible to implement, but the alternative solutions mentioned above work well enough for all the known use cases (mainly related to responsive web development) so far. Hence my intention is to get to know any common enough use cases which are not covered by those alternative solutions.

**Comment by im-mike** [comment]
Thank you for your reply and providing alternatives, however these do not work in my scenario. I have three screens in my setup, I have maximised chrome window where I have the page open that I'm working on the first screen and I have DevTools on the second screen so the code does not cover the page on the first screen at all. 

I understand that this might be chrome limitation not to go outside of the browser windows, so it's ok if this cannot be done.

Another solution I can think of would be to maximise the browser window to two screens but then have the windows split in half vertically, so half of the window (for example left side) would be the page and the other half would be your extension with code.

**Comment by webextensions** [comment]
@im-mike 
Since you are able to have Chrome DevTools open with large size, I would recommend using Google Chrome's workspaces feature. Reference: https://www.youtube.com/watch?v=thGaLbbKsW0

The main aim of this extension is to bridge the gap which is left empty by native tools. For your use-case, potentially with a learning curve, setting up Chrome workspace feature would be a more powerful solution.

My resistance towards implementing this particular feature is that there are good enough or even better alternatives possible. By saving time in not doing that, would lead to better focus for the tasks listed at https://github.com/webextensions/live-css-editor/blob/master/TODO.md

**Also, were you able to check if the "Watch CSS files to apply changes automatically" feature fits your use case?** Since you have multiple monitors, I believe it might be slightly easier for you to edit the CSS files in your favorite code editor in a separate window and the CSS changes would reflect automatically.

**Comment by XeroxDev** [comment]
I would love to see this issue reopened and worked on, because in my work we really need this feature. We are working mostly on remote systems (where we are not allowed to install something like live-server or live-css) And if you use the Responsive Design Mode in firefox or chrome, you can only see about 20% of the page (or you can't write stuff) I've also looked in the WebStorm and VSCode extension store, if there is a wrapper or alternative but no.

May I able to convince you, to work on this feature? Or is it possible, to write maybe a wrapper for the JetBrains IDE family and / or VSCode?

**Comment by webextensions** [comment]
@XeroxDev @im-mike 
This feature is now implemented and the publish has been initiated on Chrome Web Store for the latest version (v8.9.0). It should become available within next few hours/days.
