### ISSUE TITLE
Font Issue Fix

### ISSUE THREAD

**Issue by Vizlox** [webextensions/live-css-editor#41]
So, on my device (and I presume others, not sure if it's on everyone's) the font doesn't load properly in Magic CSS, defaulting to Times New Roman instead of Monospace. I had the same issue on a style sheet I was making and realized the solution, so it would apply the same here. 

For whatever reason, "font-family: monospace" no longer works. The solution is to use "font-family Courier New", which is the actual font that used to get pulled whenever monospace was entered.

I've plugged ".CodeMirror span { font-family: Courier New; }" into Stylish and set it to automatically load on every page, so the issue with Magic CSS is gone for me. It's a good enough solution until it gets fixed in the source.

**Comment by webextensions** [comment]
@Vizlox 
A potential fix for the issue has been added in https://github.com/webextensions/live-css-editor/commit/1120b407c5ea5949b989811daa2d8f949c1e358e

It would be available v8.0.5 onwards.

In the meantime, kindly try the potential fix on your machine to verify if the following CSS code solves the issue:
```css
.CodeMirror span {
    font-family: monospace, "Courier New" !important;
}
```
The `monospace` value is still useful because the default font on non-Windows OS can be different. eg: On Linux, "Courier New" is much lighter than the default monospace font.

Marking resolved under assumption that it would work out fine :-)

If the above mentioned solution doesn't work out well, then I would request you to figure out a way to reproduce it and reopen this issue.
