### ISSUE TITLE
Cannot connect to the local live-css server

### ISSUE THREAD

**Issue by colourxb** [webextensions/live-css-editor#44]
I'm having trouble connect to the live-css server as I do from localhost on Mac. I was launching the server as instructed on the prompt window of the web extension however it was only running with http but the extension was looking for https. 

I can access the server directly from Chrome after I launched the server on my terminal locally. Below information shown to indicate the live-css dev server is up running under port 3456. 

> live-css server is available at any of the following addresses:
>     http://10.249.74.160:3456/
>     http://127.0.0.1:3456/
>     http://localhost:3456/

However, on the Settings page of the extension, I got below error as it seems requires my live-css server running under https vs. the http protocol to be accessed by the extension to allow automatic refresh upon every time I reload the target page.

> This feature is meant for use during web development. You need to run a development server, called live-css, for using the features "Edit file" and "Watch CSS files to apply changes automatically".
> Step 1:
> Install Node JS Download Help
> Step 2:
> Install live-css server Link Help Extra
> npm install -g @webextensions/live-css@8
> Step 3:
> Start live-css server in your project folder
> live-css
> Step 4:
> Enter following details based on previous command's output
> Server path: (eg: https://github.com:3456)
> https://localhost: 3456
> You are not connected. Is live-css server running?
>

For now, I have to manually click on the icon to apply my hacked css.

Please kindly suggest.

OS：MacOS Catalina v10.15.4
Browser：Google Chrome v81.0.4044.113 (Official Build) (64-bit)
Node JS version：v12.6.1
live-css version: 8.0.3
Site I'm working on：Firm internal website (Altation platform)

**Comment by webextensions** [comment]
@colourxb 
It appears that you are trying to run the extension on the wrong webpage.

For example, in the case you have described, it seems that you are running it on webpage under the `https://github.com/` origin, while your `live-css` server would be running under origin `http://localhost/`. Due to security restrictions, `live-css` server wouldn't be able to run on that page since it would be a cross origin request. As a solution, try to open your webpage, say `http://localhost/example.html` and then run the `live-css` server and connect to it it by running the extension.

If it still doesn't work, then we shall further investigate with the following details:
* HTTP response header details (via Network Panel) of your webpage (say `http://localhost/example.html`)
* and if possible, a full video (showing the address bar and the Console Panel and Network Panel activity, like request headers and response headers of various requests)

**Comment by colourxb** [comment]
Thanks. It seems that live-css won't work cross domain anyways. What I'm trying to achieve is to hack the original css on a third-party website (say https://altation.com) by having your extension automatically remembers the page I'm visiting/targeting, and apply the hacked/customized css format automatically whenever I visit the site page. From what you've described. Seems this is not the use case of live-css server. So I need to have live-css run on the target site to be able to apply real time css updates on the fly otherwise what I can do is to manually click on the icon and refresh?

**Comment by webextensions** [comment]
It appears that you are looking for the "Apply styles automatically" feature (it is the pin-icon, right next to the plus icon).

**Comment by colourxb** [comment]
That's exactly what I was looking for. Thanks a lot. This marks my day. I love this tool!
