### ISSUE TITLE
"Option to reapply styles automatically" not obvious

### ISSUE THREAD

**Issue by dustball** [webextensions/live-css-editor#48]
The docs say "Option to reapply styles automatically" but I don't see this anywhere in the Opera extension.

**Comment by webextensions** [comment]
@dustball 
The process for extension approval for Opera (and Firefox) have been too much time-taking and/or restrictive. So, the version there in Opera is pretty outdated. Because of that, I didn't spend much time in updating there.

Since in Opera one can also install Chrome extensions, **I would recommend directly installing it from https://chrome.google.com/webstore/detail/live-editor-for-css-less/ifhikkcafabcgolfjegfcgloomalapol**

I hope that helps.

Leaving the issue open for now. Will mark it resolved when the latest version gets published on Opera.

**Comment by webextensions** [comment]
Added a note regarding this issue in TODO.md at https://github.com/webextensions/live-css-editor/commit/aad29992bfe739eb72ee6b856019babf4b07df8c

Closing this issue.
