### ISSUE TITLE
"More Options" doesn't work

### ISSUE THREAD

**Issue by Watslock** [webextensions/live-css-editor#5]
Chrome  60.0.3112.90

Clicking  "More Options"  - nothing happens

**Comment by webextensions** [comment]
Thanks for reporting.

I can reproduce it intermittently. Will work on a fix.

**Comment by webextensions** [comment]
This is still happening intermittently, either due to a bug in Chrome or probably due to some other extension/chrome-devtools interfering with some message passing in Magic CSS extension.

I have still not figured out the exact set of steps to follow for replicating this bug.

Till the issue is fixed, as a workaround, one may go to chrome://extensions and click on the "Options" corresponding to Magic CSS extension.

**Comment by webextensions** [comment]
The following commit attempts to fix the issue:
https://github.com/webextensions/live-css-editor/commit/8711423ba237cceb8fb156a52414345cdaf70356 (An attempt to fix a message passing issue in the extension and bumped version to 6.2.14)

Hopefully now the problem would go away.

Kindly reopen if you still face this issue with Magic CSS v6.2.14 onwards.
