### ISSUE TITLE
Issue with scroll

### ISSUE THREAD

**Issue by Nikodemsky** [webextensions/live-css-editor#58]
Hi, 

i have weird problem with scrolling, which i already mentioned on chrome extensions page, you can see the issue here on video:
https://w3wg.com/2020-10-12%2004-33-21.mp4

* The steps to reproduce is simple, just write enough code to make scrollbar appear. No need to copy&paste, it happens every time when there's enough code to scroll.

Technicals:
* I'm using chrome x64
* Win10/Enterprise x64
* It happens only on the specific website
* List of active addons on chrome:
![addons2](https://user-images.githubusercontent.com/14090596/95699732-98288080-0c45-11eb-88f1-2fd9971b2f39.png)
- i have already tried disabling those, but still no luck.

**Comment by Nikodemsky** [comment]
I can provide credentials for basic auth to specified website, just give me email or something, so it won't go on public :)

**Comment by webextensions** [comment]
@Nikodemsky 
Can you DM the details to our Twitter account @webextensions ?

**Comment by Nikodemsky** [comment]
i can't dm you for some reason, even after following you(@GamerMemories), can you check it?

**Comment by Nikodemsky** [comment]
ok i've made copy of this particular website:
http://smietnik.w3wg.com
- it have same issue

**Comment by webextensions** [comment]
@Nikodemsky 
Thank you for providing the way to reproduce the issue.

It was happening because of smooth scroll behavior (`* { scroll-behavior: smooth; }` in http://smietnik.w3wg.com/wp-content/themes/kwiatkowski-child/wg.css)

The issue has now been fixed (by overriding the related CSS for the extension UI) with the following change:
https://github.com/webextensions/live-css-editor/commit/99ec785e2f427c369fa772d532252bde8ac35164

The fix would be available with the next update of the extension (it has been submitted for review in Chrome Web Store and it should be available within few hours or few days).
