### ISSUE TITLE
does not activate at browser (re-)start

### ISSUE THREAD

**Issue by SkyCharger001** [webextensions/live-css-editor#8]
My intent was to use this to remove some unseemly margin-spacing from a few sites to reduce the amount of scrolling needed, but it looks like the add-on must be manually activated in order to have any effect.

**Comment by webextensions** [comment]
@SkyCharger001 
This issue is same as https://github.com/webextensions/live-css-editor/issues/2 (Changes aren't applied after reload until extension is opened)

More detailed reason behind this is provided in the comment https://github.com/webextensions/live-css-editor/issues/2#issuecomment-308937065

I have added a TODO task for this at https://github.com/webextensions/live-css-editor/blob/master/TODO.md under "Improvements".

Though it might take some time before I look into it.

Closing this issue for now.
