### ISSUE TITLE
Update extension for firefox and edge

### ISSUE THREAD

**Issue by wordpure** [webextensions/live-css-editor#88]
The extension versions of firefox and edge are stuck at 8.10.2 and 8.9.0 respectively, hope to update to the latest 8.18.6.

**Comment by webextensions** [comment]
@wordpure 
While it is our intention to provide the updated version for all the environments, please find below the primary reasons about why we don't actively update the extension on all the browsers:
* https://github.com/webextensions/live-css-editor/issues/48#issuecomment-638333582
* https://github.com/webextensions/live-css-editor/issues/49#issuecomment-779580848

Since in Edge and Opera, one can also install Chrome extensions, I would recommend directly installing it from https://chrome.google.com/webstore/detail/live-editor-for-css-less/ifhikkcafabcgolfjegfcgloomalapol

We do plan to sync up the release in all the browsers in near future with active efforts (https://github.com/webextensions/live-css-editor/commit/aad29992bfe739eb72ee6b856019babf4b07df8c), but it might still be a few months away.
