### ISSUE TITLE
Entire window moves while trying to select text in editor

### ISSUE THREAD

**Issue by voviks21** [webextensions/live-css-editor#9]
Please disable window moving by drag in textarea,
instead of text selection window start to move

**Comment by webextensions** [comment]
Hi ... it should not happen like that ... does it happen only on some specific webpage ?

For example, I can select text properly if I run it on this page on GitHub. I am using the extension for Chrome browser.

Can you provide any more details like webpage URL + browser + OS so that I can replicate and fix the issue :-)

**Comment by voviks21** [comment]
@webextensions , it happens on **all** pages. It starts after 5+ minutes of using editor, and after several clicks i can select text instead of moving window. Browser: old Chrome 51.0.2704.106 (64-bit), Windows 7.
I'll try to reproduce this bug.

**Comment by webextensions** [comment]
@voviks21 

I believe it must be happening when the selection attempt was started from a bracket character ... eg: '{' and '}' ?

I had fixed that bug around 2 months ago but forgot to release a new version :-)

Reference: https://github.com/webextensions/live-css-editor/commit/7c92a393dc20644340d26b1ca69e4de43b7b5a82

I'll make a new release and close this issue. Feel free to reopen this if you are still face this issue v6.2.23 onwards (which should be available in a few minutes).
